### PR TITLE
Allow running files and adding a Zig example

### PR DESCRIPTION
**Pull request by VarLad**
Issue - Redirecting of error doesn't work with Zig, giving this error 
Screenshot from 2021-06-22 19-29-43

### CODE REVIEW

**Comment by VarLad** [comment]
@

**Comment by VarLad** [comment]
@franko Any way to get the redirection working？

**Comment by VarLad** [comment]
Users say it doesn't work in other languages as well

**Comment by franko** [comment]
I will be glad to help with this but I am confused. This is a PR that does something meaningful and at the same time you are rising an issue with redirecting standard error.

I will begin by first fixing the issue if I can. Could you please precise a little bit better the problem ? It is to be sure I am going to work in the right direction.

Just to add a little bit to the context: I am not the author of the console plugin, rxi is the author and I just made some adaptations for lite-xl. I don't use myself the console plugin but I will be glad to work on some improvements, just give please more details about the problem you encountered and what you want to accomplish.

**Comment by VarLad** [comment]
@franko Thanks for reaching out
81343656-49325a00-90ad-11ea-8647-ff39d8f1d730
As given here, I expect the the cursor to the line where the error occurs
Instead, I get the error from the image in the issue in my log

**Pull request closed without merging**
